In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('anime.csv')

In [4]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

In [5]:
df.tail()

    Rank                                              Title  Score
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

In [6]:
describe = df.describe()
print(describe)

           Rank     Score
count  50.00000  50.00000
mean   25.50000   8.88320
std    14.57738   0.11722
min     1.00000   8.71000
25%    13.25000   8.79000
50%    25.50000   8.85500
75%    37.75000   8.99000
max    50.00000   9.10000

In [7]:
df.dtypes

Rank       int64
Title     object
Score    float64
dtype: object